title: Puslapio pavadinimas
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#00003c'
    - '#ffffd1'
    - '#134150'
    - '#ded7a1'
    - '#869a7e'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
name: Testas
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.26198
layout_spectrum: 0.7126642
