name: Testas
favicon: null
layout_spectrum: 0.75811
typography_spectrum: 0.26198
title: Puslapio pavadinimas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00003c'
    - '#ffffd1'
    - '#134150'
    - '#ded7a1'
    - '#869a7e'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
