name: Testas
favicon: null
layout_spectrum: 0.7621795022860169
typography_spectrum: 0.04283144837245345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.460215370869264
  lightness: 0.5093424341175705
  saturation: 0.49757916340604424
  rhythmicContrast: 0.39668762939982116
purpose: []
